README.md, lib/add.js, lib/addRemote.js, lib/addSubmodule.js, lib/branch.js, lib/checkout.js, lib/checkoutFiles.js, lib/clone.js, lib/commit.js, lib/exec.js, lib/init.js, lib/merge.js, lib/pull.js, lib/push.js, lib/reset.js, lib/revParse.js, lib/rm.js, lib/status.js, lib/tag.js, lib/updateSubmodule.js
Add a `quiet` option to every function, preventing output on `gutil.log`.
=> Add `quiet` option

lib/commit.js
As the [git docs mention](http://git-scm.com/docs/git-commit), if multiple -m options are given to `git commit`, their values are concatenated as separate paragraphs (lines). Since javascript now supports multiple line string literal templates in ES6, we should convert multi line string literals to unique -m entries when working with git's cli.
=> break up multiline comment messages

README.md, examples/gulpfile.js, lib/commit.js, package.json, test/commit.js
I have a use case which requires me to pass a raw argument string to git commit. A user will set the message in this raw string. Setting disableMessageRequirement to true will allow libraries to disable the sensible defaults in special cases.
=> Adds disableMessageRequirement option

README.md, lib/commit.js, test/_util.js, test/commit.js
This option is useful in specific cases where you might want to call commit, but not want to have any paths added to the end of the commit string. Specifically, if you're providing it via raw arguments, manually, instead.
Tests, docs included.
=> Adds disableAppendPaths option to git.commit.

README.md, examples/gulpfile.js, lib/commit.js, test/commit.js
Multiple lines should happen by passing an array of messages as message
instead of relying upon finding newline characters. A given message can
have newline characters without spawning a new -m argument. This fixes
this functionality.
=> Edit multiple line commit message functionality

README.md, lib/commit.js, lib/exec.js, lib/status.js
Add `maxBuffer` option to `git.commit` and `git.status` commands.
This option is directly bound to the same option of the `child_process.exec` command.
Also update *README* as well.
=> Add 'maxBuffer' option

README.md, lib/removeRemote.js, test/removeRemote.js
Hi Steve
I'm trying to use git-gulp to create a gulp script to deploy a website by pushing a git repo to the web server.
It would really help if I could have removeRemote functionality to compliment addRemote
I've updated the readme and added a test. 
Thanks
=> Remove remote

README.md, lib/commit.js, test/commit.js
Closes #98
Adds tests, readme and code that allows for watching data events during git commit.
=> add option to listen to commit progress

README.md, lib/push.js, lib/tag.js
This pull request addresses the following issues:
- allow to push tags directly to a repository;
- let the `tag()` method function as getter to obtain a list of all tags.
=> Allow `null` as branch name when pushing, use `tag()` method as getter

lib/tag.js
The output from `git.tag` with no arguments wasn't being passed to the callback function.
=> Pass tag output to callback

README.md, lib/fetch.js, lib/pull.js, lib/push.js
Enables users to specify `branch` parameter as an _array_ of strings in _pull_, _push_ and _fetch_ `git` commands.
Example:
```javascript
git.push('origin', ['develop', 'master'], { quiet: true, args: '--tags' }, done);
```
Generates the following valid shell command:
```sh
$ git push origin develop master --tags
```
=> Allow multiple refspecs on fetch, pull and push

lib/tag.js
This change properly escapes the tag message (`message`) just like the tag name (`version`) is escaped. Without the change, the double quotes in `'"message" test'` are not kept and other problems could occur.
=> Fix git tag message escaping

README.md, examples/gulpfile.js, lib/commit.js, test/_util.js, test/commit.js
Adds support for newlines in commits, either by passing a message with newlines or an array of messages with the option `multi`.
Closes #122
=> Add newline support for commit

README.md, lib/tag.js
It is common to create an annotated tag with an empty message as so:
`$ git tag -a -m '' 'v1.2.3'`
This change does not break other functionality and adds an example in the README file.
=> Git tag allow empty message

test/commit.js
There is an intermittent error in the tests you can see [here](https://travis-ci.org/stevelacy/gulp-git/jobs/147330352#L265). It is caused by a file in a commit test (`util.testOptionsFiles[4]`) to be added and committed. Since the same file is added and committed in a test above, the commit fails.
Also, the `data` event is now called twice and causes `done()` to be executed twice therefore `gitS.once` is used instead of `gitS.on`.
Some trailing whitespaces were also removed from the file.
=> Fix commit test error

lib/commit.js
same as https://github.com/stevelacy/gulp-git/pull/118
not sure why the tests failed in previous PR but it worked on my machine
=> don't return error when nothing to commit.

lib/branch.js
`git branch --contains` returns through stdout, this is the result of the operation.
=> support git branch --contains

README.md
I could not find this option in the docs but it seems to be working.
=> Add git.add({ cwd: '/cwd/path' }) option to ReadMe

README.md
based on https://github.com/stevelacy/gulp-git/pull/172 but without git.tag
=> added the possiblity to use an array of strings as message in git.commit

lib/add.js, lib/addRemote.js, lib/addSubmodule.js, lib/branch.js, lib/catFile.js, lib/checkout.js, lib/checkoutFiles.js, lib/clean.js, lib/clone.js, lib/commit.js, lib/diff.js, lib/exec.js, lib/fetch.js, lib/init.js, lib/merge.js, lib/pull.js, lib/push.js, lib/removeRemote.js, lib/reset.js, lib/revParse.js, lib/rm.js, lib/stash.js, lib/status.js, lib/tag.js, lib/updateSubmodule.js, package.json, test/add.js, test/main.js, test/rm.js, test/status.js
Hi,
Since `gulp-util` has been deprecated, this PR replace `gulp-util` with alternative individual modules. Please see: https://github.com/gulpjs/gulp-util
=> core: remove deprecated gulp-util dependency

README.md, examples/gulpfile.js, lib/commit.js, test/commit.js
Hi there!
First off, great work on this plugin!
While setting up a new project and using gulp-bump, I wanted to achieve something like the following:
```javascript
return gulp.src([
'package.json',
'app/manifest.json'
], {
base: './'
})
// bump the version number in those files
.pipe(bump({
type: importance
}))
// save it back to filesystem
.pipe(gulp.dest('./'))
// commit the changed version number
.pipe(through.obj((file, enc, cb) => {
const bumpData = file.bumpData;
newVersion = bumpData.new;
}))
.pipe(git.commit(() => `[build] Version ${newVersion}`))
// read only one file to get the version number
.pipe(filter('package.json'))
// **tag it in the repository**
.pipe(tagVersion())
```
I wrestled with it for a while, trying to achieve it without code changes (i.e. with some kind of …
=> added the possibility to use a function as message in git.commit
